### ISSUE TITLE
Private wiki

### ISSUE THREAD

**Issue by cybrwushl93** [scragg0x/realms-wiki#60]
First of all I like this wiki system, it's really nice :smile: :+1: 

But when I installed it, i found two things, that are improvable.

It would be nice, to use realms-wiki as a "private" wiki. So nobody can sees anything until he is logged in. This way I like to use it. So I solved this problem by adding to every route in the views.py `@login_required`. Maybe theres a way to make this configurable?

And after all the installation is a bit complicated. Are there ways to simplify this?

**Comment by scragg0x** [comment]
It's been suggested here: https://github.com/scragg0x/realms-wiki/issues/54

I will work on this feature when I get a chance or pull from someone that has already done it.  Seems like it should be a config value when a simple condition on a few routes.

> And after all the installation is a bit complicated. Are there ways to simplify this?

Installation should just be `pip install realms-wiki` (for those that don't plan on changing source).  Vagrant should make development relatively quick since it provisions everything automatically.  Then there is docker image.  If you have a suggestion let me know in a separate issue.
